/* ============================================================
   QUIZ QUESTION BANK  —  KBC-style game
   Each category has 15 questions ordered roughly easy -> hard.
   Format: { q: "question", o: ["A","B","C","D"], a: correctIndex }
   To add your own category, copy a block and change the questions.
   ============================================================ */

const CATEGORIES = {
  ai: {
    name: "Artificial Intelligence",
    icon: "🤖",
    blurb: "Robots, machine learning & the future",
    questions: [
      { q: "What does 'AI' stand for?", o: ["Automatic Input", "Artificial Intelligence", "Advanced Internet", "Applied Information"], a: 1 },
      { q: "Which company created ChatGPT?", o: ["Google", "Meta", "OpenAI", "Microsoft"], a: 2 },
      { q: "A computer program that chats like a human is called a?", o: ["Chatbot", "Browser", "Compiler", "Firewall"], a: 0 },
      { q: "What does 'ML' commonly stand for in AI?", o: ["Main Logic", "Machine Learning", "Mega Load", "Manual Language"], a: 1 },
      { q: "Which of these is Apple's AI voice assistant?", o: ["Alexa", "Cortana", "Siri", "Bixby"], a: 2 },
      { q: "Which programming language is most popular for AI/ML?", o: ["HTML", "Python", "PHP", "Swift"], a: 1 },
      { q: "What is the name of Google's AI chatbot?", o: ["Gemini", "Copilot", "Grok", "Claude"], a: 0 },
      { q: "Deep Learning is inspired by which human organ?", o: ["Heart", "Liver", "Brain", "Eye"], a: 2 },
      { q: "Training a model on labeled data is called?", o: ["Supervised Learning", "Blind Learning", "Random Learning", "Manual Coding"], a: 0 },
      { q: "The 'Turing Test' checks if a machine can?", o: ["Run fast", "Seem human", "Store data", "Draw images"], a: 1 },
      { q: "The basic unit of a neural network is called a?", o: ["Cell", "Neuron", "Byte", "Pixel"], a: 1 },
      { q: "Which is a large language model made by Meta?", o: ["LLaMA", "Gemini", "GPT", "Watson"], a: 0 },
      { q: "'GAN' in AI stands for?", o: ["Global Access Network", "Generative Adversarial Network", "General AI Node", "Graphic Array Number"], a: 1 },
      { q: "Which IBM computer beat world chess champion Garry Kasparov in 1997?", o: ["Watson", "Deep Blue", "HAL 9000", "AlphaGo"], a: 1 },
      { q: "Who is often called the 'father of Artificial Intelligence'?", o: ["Alan Turing", "John McCarthy", "Elon Musk", "Geoffrey Hinton"], a: 1 },
    ],
  },

  gk: {
    name: "General Knowledge",
    icon: "🌍",
    blurb: "A bit of everything",
    questions: [
      { q: "How many continents are there on Earth?", o: ["5", "6", "7", "8"], a: 2 },
      { q: "What is the capital of India?", o: ["Mumbai", "Kolkata", "New Delhi", "Chennai"], a: 2 },
      { q: "Which planet is known as the Red Planet?", o: ["Venus", "Mars", "Jupiter", "Saturn"], a: 1 },
      { q: "How many colours are there in a rainbow?", o: ["5", "6", "7", "8"], a: 2 },
      { q: "Which is the largest ocean on Earth?", o: ["Atlantic", "Indian", "Arctic", "Pacific"], a: 3 },
      { q: "How many players are in a cricket team?", o: ["9", "10", "11", "12"], a: 2 },
      { q: "Which gas do plants absorb from the air?", o: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], a: 1 },
      { q: "The Great Wall is located in which country?", o: ["Japan", "India", "China", "Korea"], a: 2 },
      { q: "Which is the smallest planet in our solar system?", o: ["Mars", "Mercury", "Venus", "Pluto"], a: 1 },
      { q: "Which country is called the 'Land of the Rising Sun'?", o: ["China", "Thailand", "Japan", "Korea"], a: 2 },
      { q: "The currency of Japan is the?", o: ["Won", "Yuan", "Yen", "Rupee"], a: 2 },
      { q: "Who wrote the Indian national anthem?", o: ["Bankim Chandra", "Rabindranath Tagore", "Mahatma Gandhi", "Sarojini Naidu"], a: 1 },
      { q: "Mount Everest lies in which mountain range?", o: ["Andes", "Alps", "Himalayas", "Rockies"], a: 2 },
      { q: "Who was the first Prime Minister of India?", o: ["Sardar Patel", "Jawaharlal Nehru", "B. R. Ambedkar", "Rajendra Prasad"], a: 1 },
      { q: "Which is the longest river in the world?", o: ["Amazon", "Ganga", "Nile", "Yangtze"], a: 2 },
    ],
  },

  science: {
    name: "Science & Technology",
    icon: "🔬",
    blurb: "Physics, chemistry, biology & more",
    questions: [
      { q: "What is H₂O commonly known as?", o: ["Salt", "Water", "Oxygen", "Acid"], a: 1 },
      { q: "Which planet is closest to the Sun?", o: ["Earth", "Venus", "Mercury", "Mars"], a: 2 },
      { q: "What is the chemical symbol for gold?", o: ["Go", "Gd", "Au", "Ag"], a: 2 },
      { q: "Which gas do humans need to breathe to live?", o: ["Carbon dioxide", "Oxygen", "Nitrogen", "Helium"], a: 1 },
      { q: "What force pulls objects toward the Earth?", o: ["Magnetism", "Friction", "Gravity", "Tension"], a: 2 },
      { q: "How many bones are in the adult human body?", o: ["201", "206", "210", "196"], a: 1 },
      { q: "What is the powerhouse of the cell?", o: ["Nucleus", "Ribosome", "Mitochondria", "Membrane"], a: 2 },
      { q: "Which metal is liquid at room temperature?", o: ["Iron", "Mercury", "Aluminium", "Copper"], a: 1 },
      { q: "Who proposed the theory of relativity?", o: ["Newton", "Einstein", "Galileo", "Tesla"], a: 1 },
      { q: "The hardest natural substance on Earth is?", o: ["Gold", "Iron", "Diamond", "Quartz"], a: 2 },
      { q: "'DNA' stands for?", o: ["Deoxyribonucleic Acid", "Dual Nucleic Atom", "Direct Nuclear Acid", "Dynamic Nano Array"], a: 0 },
      { q: "The study of living organisms is called?", o: ["Geology", "Biology", "Physics", "Ecology"], a: 1 },
      { q: "Who is credited with formulating the laws of motion & gravity?", o: ["Isaac Newton", "Albert Einstein", "Nikola Tesla", "Charles Darwin"], a: 0 },
      { q: "The most abundant gas in Earth's atmosphere is?", o: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], a: 2 },
      { q: "The speed of light is approximately?", o: ["3,000 km/s", "30,000 km/s", "3,00,000 km/s", "3,000,000 km/s"], a: 2 },
    ],
  },

  sports: {
    name: "Sports",
    icon: "🏏",
    blurb: "Cricket, football, Olympics & more",
    questions: [
      { q: "How many players are on a football (soccer) team on the field?", o: ["9", "10", "11", "12"], a: 2 },
      { q: "In cricket, a hit that clears the boundary rope is worth?", o: ["2 runs", "4 runs", "6 runs", "8 runs"], a: 2 },
      { q: "How many rings are on the Olympic flag?", o: ["4", "5", "6", "7"], a: 1 },
      { q: "In tennis, a score of zero is called?", o: ["Nil", "Love", "Duck", "Blank"], a: 1 },
      { q: "Sachin Tendulkar is associated with which sport?", o: ["Hockey", "Cricket", "Tennis", "Football"], a: 1 },
      { q: "How many players are on a basketball team on court?", o: ["5", "6", "7", "11"], a: 0 },
      { q: "Which country won the FIFA World Cup 2022?", o: ["France", "Brazil", "Argentina", "Germany"], a: 2 },
      { q: "The Olympic Games are held every how many years?", o: ["2", "3", "4", "5"], a: 2 },
      { q: "In which sport would you perform a 'slam dunk'?", o: ["Volleyball", "Basketball", "Tennis", "Cricket"], a: 1 },
      { q: "Usain Bolt is world famous in which sport?", o: ["Swimming", "Cycling", "Sprinting", "Boxing"], a: 2 },
      { q: "A full marathon is approximately how long?", o: ["21 km", "42 km", "50 km", "100 km"], a: 1 },
      { q: "Which sport is nicknamed the 'gentleman's game'?", o: ["Golf", "Cricket", "Tennis", "Polo"], a: 1 },
      { q: "In which country did the sport of table tennis originate?", o: ["China", "USA", "England", "Japan"], a: 2 },
      { q: "The term 'grand slam' is used in which sport?", o: ["Football", "Tennis", "Hockey", "Rugby"], a: 1 },
      { q: "Which country has won the most men's ODI Cricket World Cups?", o: ["India", "West Indies", "Australia", "England"], a: 2 },
    ],
  },

  computers: {
    name: "Computers & Programming",
    icon: "💻",
    blurb: "For the tech-savvy",
    questions: [
      { q: "What does 'CPU' stand for?", o: ["Central Processing Unit", "Computer Power Unit", "Central Print Unit", "Core Program Utility"], a: 0 },
      { q: "Which of these is an operating system?", o: ["Google", "Windows", "Intel", "Chrome"], a: 1 },
      { q: "Which company developed the Windows OS?", o: ["Apple", "Microsoft", "IBM", "Google"], a: 1 },
      { q: "'HTML' stands for?", o: ["HyperText Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink Text Mode Language"], a: 0 },
      { q: "'www' stands for?", o: ["World Wide Web", "Web World Wide", "Wide World Web", "World Web Wide"], a: 0 },
      { q: "Which language is mainly used to style web pages?", o: ["HTML", "CSS", "SQL", "C++"], a: 1 },
      { q: "'RAM' stands for?", o: ["Read Access Memory", "Random Access Memory", "Rapid Active Memory", "Run All Memory"], a: 1 },
      { q: "Who is a co-founder of Microsoft?", o: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Larry Page"], a: 1 },
      { q: "Which symbol starts a single-line comment in Python?", o: ["//", "#", "<!--", "--"], a: 1 },
      { q: "'URL' stands for?", o: ["Uniform Resource Locator", "Universal Reading Link", "User Register Login", "Unique Reference Label"], a: 0 },
      { q: "Which data structure works on 'First In First Out'?", o: ["Stack", "Queue", "Tree", "Graph"], a: 1 },
      { q: "'GPU' stands for?", o: ["General Power Unit", "Graphics Processing Unit", "Global Program Utility", "Gigabyte Processing Unit"], a: 1 },
      { q: "The binary representation of the decimal number 2 is?", o: ["01", "10", "11", "20"], a: 1 },
      { q: "Which of these is a version control system?", o: ["Git", "Zip", "FTP", "SQL"], a: 0 },
      { q: "Which company originally created the Java language?", o: ["Microsoft", "Oracle", "Sun Microsystems", "Apple"], a: 2 },
    ],
  },

  movies: {
    name: "Bollywood & Movies",
    icon: "🎬",
    blurb: "Lights, camera, action!",
    questions: [
      { q: "Who is popularly called the 'King of Bollywood'?", o: ["Salman Khan", "Shah Rukh Khan", "Aamir Khan", "Akshay Kumar"], a: 1 },
      { q: "Which actor is nicknamed 'Big B'?", o: ["Dharmendra", "Amitabh Bachchan", "Rajesh Khanna", "Dilip Kumar"], a: 1 },
      { q: "The dialogue 'Mogambo khush hua' is from which film?", o: ["Sholay", "Mr. India", "Koyla", "Karma"], a: 1 },
      { q: "'3 Idiots' and 'Dangal' both starred which actor?", o: ["Shah Rukh Khan", "Aamir Khan", "Salman Khan", "Hrithik Roshan"], a: 1 },
      { q: "Which city is the hub of the Hindi film industry?", o: ["Delhi", "Chennai", "Mumbai", "Hyderabad"], a: 2 },
      { q: "'Baahubali' was directed by?", o: ["Rajkumar Hirani", "S. S. Rajamouli", "Karan Johar", "Rohit Shetty"], a: 1 },
      { q: "Deepika Padukone made her Bollywood debut with?", o: ["Om Shanti Om", "Cocktail", "Piku", "Padmaavat"], a: 0 },
      { q: "The song 'Jai Ho' features in which film?", o: ["Lagaan", "Slumdog Millionaire", "Swades", "Rang De Basanti"], a: 1 },
      { q: "Ranbir Kapoor belongs to which famous film family?", o: ["Khan", "Kapoor", "Bachchan", "Deol"], a: 1 },
      { q: "Which composer, known as the 'Mozart of Madras', won Oscars?", o: ["Pritam", "A. R. Rahman", "Shankar Mahadevan", "Vishal-Shekhar"], a: 1 },
      { q: "The film 'Lagaan' is set during which era?", o: ["Mughal Empire", "British Raj", "Independence", "Modern India"], a: 1 },
      { q: "Which song from 'RRR' won an Academy Award?", o: ["Naatu Naatu", "Jai Ho", "Chaiyya Chaiyya", "Dola Re"], a: 0 },
      { q: "India's highest award in cinema is the?", o: ["Filmfare Award", "National Award", "Dadasaheb Phalke Award", "IIFA Award"], a: 2 },
      { q: "The classic film 'Sholay' was released in which decade?", o: ["1960s", "1970s", "1980s", "1990s"], a: 1 },
      { q: "'PK' and 'Sanju' were directed by?", o: ["Karan Johar", "Rajkumar Hirani", "Anurag Kashyap", "Zoya Akhtar"], a: 1 },
    ],
  },
};
